### ISSUE TITLE
Command Line / Automation

### ISSUE THREAD

**Issue by RappsFF7** [pruby/mc_recompress#1]
This is an enhancement request more than an issue.

The idea behind this compressor is great, and having a GUI is a nice touch... however backups usually wind up being an automated process. Seeing that the program auto launches a GUI when running with the command "java -jar mcrecompress.jar" I can only imagine that it's GUI only.

It would be great if this had a command line .jar and a GUI .jar (which ran those commands available in the command line .jar) so it can be used in an automated setup. Something as simple as "java -jar mcrecompress.jar -compress [source] [destination]" and "java -jar mcrecompress.jar -decompress [source] [destination]" would be plenty.

**Comment by pruby** [comment]
Done, command line in latest package is:

java -jar mcrecompress.jar --compress file.mca
java -jar mcrecompress.jar --decompress file.mri.bz2

These compress and decompress within the same directory, but don't delete the original file so you have the option to move it elsewhere afterwards. It still does all its writing to a temporary file then moves in to place - if the file is created, it's intact.
